-- DB_ORGANIZER0528 ADMIN

CREATE DATABASE DB_ORGANIZER0528;
USE DB_ORGANIZER0528;


CREATE TABLE TBL_ADMIN (
	A_NO INT AUTO_INCREMENT UNIQUE,
	A_ID VARCHAR(20) NOT NULL UNIQUE,
	A_PW VARCHAR(100) NOT NULL,
	A_MAIL VARCHAR(50) NOT NULL,
	A_PHONE VARCHAR(30) NOT NULL,
	A_ROLE VARCHAR(20) DEFAULT 'ADMIN_PENDING',
	A_REG_DATE DATETIME DEFAULT NOW(),
	A_MOD_DATE DATETIME DEFAULT NOW(),
	PRIMARY KEY(A_ID)
);

SELECT * FROM TBL_ADMIN;
DELETE FROM TBL_ADMIN;
DROP TABLE TBL_ADMIN;
